---
- hosts: 
  gather_facts: no
  tasks:
   - name: set host names
     hostname:
       name: "{{ item }}"
     with_items:
       - vagrant-gluster1
       - vagrant-gluster1 

   - name: Install glusterfs server
     import_role:
       name: gluster_server
