- name: import repo key
  rpm_key:
    state: present
    key: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
    
- name : Upload the Elk repository
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: '0644'

- name : Upload the logstash repository
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: '0644'