- name: Install Java 8
  yum:
    name: java
    state: latest

- name: Install elasticsearch GPG Key
  rpm_key:
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
    
- name: Install ElasticSearch 
  yum:
    name: elasticsearch
    state: latest
    enabled: yes
  

- name: Install Kibanna
  yum:
    name: kibanna
    state: latest
    enbled: yes
  notify: resart_kibanna

- name: Install Epel Repository
  yum:
    name: epel-release
    state: latest

- name: Install Nginx
  yum:
    name: nginx
    state: latest
    enabled: yes
  notify: restart_nginx

- name: install http-tools
  yum: 
    name: httpd-tools

- name: Install Logstash
  yum: 
    name: logstash
    state: latest

