---
# handlers file for elk-stack
- name: restart_elasticsearch
  service: 
    name: elasticsearch
    state: restarted
    enabled: yes

- name: restart_kibana
  service:
    name: kibana
    state: restarted
    enabled: yes

- name: restart_nginx
  service: 
    name: nginx
    state: restarted
    enabled: yes