---
# handlers file for gluster_server
  
- name: restart ntp
  service:
    name: ntp
    state: restarted
  become: yes 

- name: restart sshd
  service: 
    name: sshd 
    state: restarted
  become: yes 