- name: Create brick Directory
  file:
    path: /opt/bricks
    state: directory


- name: Create a xfs filesystem on /dev/sdb1./dev/glustervol1/vol1
  filesystem:
    fstype: xfs
    dev: /dev/glustervol1/vol1


- name: Ensure Gluster volume is mounted.
  mount:
    src: "/dev/glustervol1/vol1"
    path: "/opt/bricks"
    fstype: xfs
    opts: "defaults"
    state: mounted

- name: Create bricks
  file:
    path: "/opt/bricks/brick1"
    state: directory

- name: update fstab
  lineinfile:
    path: "/etc/fstab"
    line: "/dev/mapper/glustervol1-vol1 /opt/bricks/ xfs defaults 1 2"
    state: present

- include_tasks: glusterd_start.yml

- name: create gluster volume
  gluster_volume:
    state: present
    name: vol1
    bricks: "/opt/bricks/brick1"
    rebalance: yes
    cluster:
      - 10.11.13.51
      - 10.11.13.52
  run_once: true


