
- name: Create a volume group on top of /dev/sdb
  lvg:
    vg: glustervol1
    pvs: "/dev/sdb"
    state: present

- name: Create a logical volume of 100.
  lvol:
    vg: glustervol1
    lv: vol1
    size: 100%FREE
    state: present

#- name: Create a lvm filesystem on /dev/sdb1
#  filesystem:
#    fstype: lvm
#    dev: glustervol1-vol1
