# tasks file for gluster_server
  - include_vars: '/Users/rob/Documents/Gluster_ansible_roles/roles/gluster_server/vars/main.yml'
  
  - name: disable firewall
    service:
      name: firewalld
      state: stopped
      enabled: no

      
  - name: Import hosts file
    import_tasks: host_file.yml

  - name: Install Epel Repository
    import_tasks: epel_repo.yml
  
  - name: Create Volume_groups
    import_tasks: lvm_create.yml
  
  - name: Install Gluster Repo
    import_tasks: gluster_repo.yml  
  
  #- name: Upgrade the OS and insure that all new installs are new
  #  import_tasks: update.yml
  
  - name: Install NTP 
    import_tasks: ntp.yml  

  - name: Install Gluster Packages
    import_tasks: install_gluster_packages.yml

  - name: Install XFS Tools
    import_tasks: xfs_tools.yml

  - name: glusterD starting
    import_tasks: glusterd_start.yml

  - name: Set up gluster peers
    import_tasks: gluster_peer.yml
  
  - name: Set up gluster Bricks
    import_tasks: add_bricks.yml

  - name: start gluster
    import_tasks: start_gluster.yml  

  


#  - name: Create Partition
#    import_tasks: create_partition.yml

#  - name: Create XFS Filesystem
#    import_tasks: xfs_filesystem:yml



