- name: Install NTP
  yum:
    name: ntp
    state: latest
  become: yes
  notify: restart ntp

- name: Install NTP Date
  yum:
    name: ntpdate
    state: latest
  become: yes
  notify: restat ntp 
