- name: Install NTP
  yum:
    name: ntp
    state: present
  become: yes
  notify: restart ntp

- name: Install NTP Date
  yum:
    name: ntpdate
    state: present
  become: yes
  notify: restat ntp 
